<?php

namespace Database\Seeders;

use App\Models\Track;
use Illuminate\Database\Seeder;

class TrackSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seedTracks = [
            [
                "id" => 1,
                "artist" => "Jean Michel Jarre",
                "album" => "Oxygène",
                "track_number" => 1,
                "genre_id" => 17,
                "name" => "Oxygène (Part I)",
                "length" => "0:07:39",
                "year" => 1977,],
            [
                "id" => 2,
                "artist" => "AllttA",
                "album" => "Facing Giants",
                "track_number" => 2,
                "genre_id" => 24,
                "name" => "More Better  (fg. II) [feat. 20syl & Mr. J Medeiros]",
                "length" => "0:02:57",
                "year" => 2017,],

            [
                "id" => 3,
                "artist" => "Zutomayo",
                "album" => "Gusare",
                "track_number" => 4,
                "genre_id" => 23,
                "name" => "Hunch Gray",
                "length" => "0:04:10",
                "year" => 2021,],
            [
                "id" => 4,
                "artist" => "Apocalyptica",
                "album" => "Inquisition Symphony",
                "track_number" => 7,
                "genre_id" => 7,
                "name" => "Inquisition Symphony",
                "length" => "0:04:59",
                "year" => 1998,],
            [
                "id" => 6,
                "artist" => "Beck",
                "album" => "Midnight Vultures",
                "track_number" => 1,
                "genre_id" => 5,
                "name" => "Nicotine & Gravy",
                "length" => "0:05:13",
                "year" => 1999,],
            [
                "id" => 7,
                "artist" => "Beck",
                "album" => "Midnight Vultures",
                "track_number" => 2,
                "genre_id" => 5,
                "name" => "Mixed Bizness",
                "length" => "0:04:10",
                "year" => 1999,],
            [
                "id" => 8,
                "artist" => "Zutomayo",
                "album" => "Gusare",
                "track_number" => 2,
                "genre_id" => 23,
                "name" => "Can't Be Right",
                "length" => "0:04:01",
                "year" => 2021,],
            [
                "id" => 9,
                "artist" => "Bryan Adams",
                "album" => "Unplugged",
                "track_number" => 7,
                "genre_id" => 1,
                "name" => "18 til I die",
                "length" => "0:03:31",
                "year" => 1997,],
            [
                "id" => 11,
                "artist" => "Bryan Adams",
                "album" => "Unplugged",
                "track_number" => 12,
                "genre_id" => 1,
                "name" => "Heaven",
                "length" => "0:04:31",
                "year" => 1997,],
            [
                "id" => 12,
                "artist" => "Dead Can Dance",
                "album" => "Dead Can Dance",
                "track_number" => 1,
                "genre_id" => 2,
                "name" => "Carnival of Light",
                "length" => "0:03:33",
                "year" => 2008,],
            [
                "id" => 13,
                "artist" => "Dead Can Dance",
                "album" => "Dead Can Dance",
                "track_number" => 2,
                "genre_id" => 2,
                "name" => "In Power we Entrust the Love Advocated",
                "length" => "0:04:12",
                "year" => 2008,],
            [
                "id" => 14,
                "artist" => "Eric Prydz",
                "album" => "Opus",
                "track_number" => 6,
                "genre_id" => 17,
                "name" => "Moody Mondays (feat. The Cut)",
                "length" => "0:04:43",
                "year" => 2016,],
            [
                "id" => 15,
                "artist" => "Eric Prydz",
                "album" => "Opus",
                "track_number" => 19,
                "genre_id" => 17,
                "name" => "Opus",
                "length" => "0:09:04",
                "year" => 2016,],
            [
                "id" => 17,
                "artist" => "Jean Michel Jarre",
                "album" => "Oxygène",
                "track_number" => 2,
                "genre_id" => 17,
                "name" => "Oxygène (Part II)",
                "length" => "0:07:49",
                "year" => 1977,],
            [
                "id" => 18,
                "artist" => "Jean Michel Jarre",
                "album" => "Oxygène",
                "track_number" => 3,
                "genre_id" => 17,
                "name" => "Oxygène (Part III)",
                "length" => "0:03:16",
                "year" => 1977,],
            [
                "id" => 20,
                "artist" => "Bryan Adams",
                "album" => "Unplugged",
                "track_number" => 11,
                "genre_id" => 1,
                "name" => "A Little Love",
                "length" => "0:03:23",
                "year" => 1997,],
            [
                "id" => 21,
                "artist" => "Apocalyptica",
                "album" => "Shadowmaker",
                "track_number" => 12,
                "genre_id" => 7,
                "name" => "Dean Man's Eyes",
                "length" => "0:09:43",
                "year" => 2015,],
            [
                "id" => 23,
                "artist" => "Lemongrass",
                "album" => "Windows",
                "track_number" => 2,
                "genre_id" => 6,
                "name" => "Imagine",
                "length" => "0:04:42",
                "year" => 2001,],
            [
                "id" => 24,
                "artist" => "Kate Bush",
                "album" => "The Kick Inside",
                "track_number" => 5,
                "genre_id" => 2,
                "name" => "The Man with the Child in His Eyes",
                "length" => "0:02:41",
                "year" => 1978,],
            [
                "id" => 25,
                "artist" => "Matsumoto Zuko",
                "album" => "Matsumoto Zuko",
                "track_number" => 2,
                "genre_id" => 17,
                "name" => "Bologna",
                "length" => "0:02:33",
                "year" => 2014,],
            [
                "id" => 26,
                "artist" => "Matsumoto Zuko",
                "album" => "Matsumoto Zuko",
                "track_number" => 3,
                "genre_id" => 17,
                "name" => "Melbourne",
                "length" => "0:03:53",
                "year" => 2014,],
            [
                "id" => 27,
                "artist" => "Mike Oldfield",
                "album" => "Amarok",
                "track_number" => 1,
                "genre_id" => 17,
                "name" => "Amarok",
                "length" => "0:01:00",
                "year" => 1990,],
            [
                "id" => 28,
                "artist" => "AllttA",
                "album" => "Facing Giants",
                "track_number" => 3,
                "genre_id" => 24,
                "name" => "Choo Choo (fg. III) [feat. 20syl & Mr. J Medeiros]",
                "length" => "0:02:35",
                "year" => 2017,],
            [
                "id" => 29,
                "artist" => "Tangerine Dream",
                "album" => "Rubycon",
                "track_number" => 2,
                "genre_id" => 17,
                "name" => "Rubycon, Part II",
                "length" => "0:17:35",
                "year" => 1975,],
            [
                "id" => 30,
                "artist" => "Tarja Turunen",
                "album" => "My Winter Storm",
                "track_number" => 2,
                "genre_id" => 7,
                "name" => "I Walk Alone",
                "length" => "0:03:53",
                "year" => 2007,],
            [
                "id" => 31,
                "artist" => "Zutomayo",
                "album" => "Gusare",
                "track_number" => 1,
                "genre_id" => 23,
                "name" => "One's Mind",
                "length" => "0:04:19",
                "year" => 2021,],
            [
                "id" => 33,
                "artist" => "Beck",
                "album" => "Midnight Vultures",
                "track_number" => 3,
                "genre_id" => 5,
                "name" => "Get Real Paid",
                "length" => "0:04:44",
                "year" => 1999,],
            [
                "id" => 34,
                "artist" => "Zutomayo",
                "album" => "Gusare",
                "track_number" => 3,
                "genre_id" => 23,
                "name" => "Obenkyou Shitoiteyo",
                "length" => "0:04:39",
                "year" => 2021,],
            [
                "id" => 35,
                "artist" => "Epica",
                "album" => "Live Station 4",
                "track_number" => 2,
                "genre_id" => 7,
                "name" => "Sensorium",
                "length" => "0:04:56",
                "year" => 2010,],
            [
                "id" => 36,
                "artist" => "Kate Bush",
                "album" => "The Kick Inside",
                "track_number" => 6,
                "genre_id" => 2,
                "name" => "Wuthering Heights",
                "length" => "0:04:29",
                "year" => 1978,],
            [
                "id" => 37,
                "artist" => "Kate Bush",
                "album" => "Hounds of Love",
                "track_number" => 2,
                "genre_id" => 2,
                "name" => "Hounds of Love",
                "length" => "0:03:03",
                "year" => 1985,],
            [
                "id" => 38,
                "artist" => "Dead Can Dance",
                "album" => "Dead Can Dance",
                "track_number" => 4,
                "genre_id" => 2,
                "name" => "Flowers of the Sea",
                "length" => "0:03:27",
                "year" => 2008,],
            [
                "id" => 39,
                "artist" => "Kate Bush",
                "album" => "Hounds of Love",
                "track_number" => 10,
                "genre_id" => 2,
                "name" => "Jig of Life",
                "length" => "0:04:04",
                "year" => 1985,],
            [
                "id" => 40,
                "artist" => "Kate Bush",
                "album" => "Hounds of Love",
                "track_number" => 11,
                "genre_id" => 2,
                "name" => "Hello Earth",
                "length" => "0:06:13",
                "year" => 1985,],
            [
                "id" => 41,
                "artist" => "Dead Can Dance",
                "album" => "Dead Can Dance",
                "track_number" => 3,
                "genre_id" => 2,
                "name" => "The Arcane",
                "length" => "0:03:48",
                "year" => 2008,],
            [
                "id" => 42,
                "artist" => "Matsumoto Zuko",
                "album" => "Matsumoto Zuko",
                "track_number" => 1,
                "genre_id" => 17,
                "name" => "Wa",
                "length" => "0:04:30",
                "year" => 2014,],
            [
                "id" => 44,
                "artist" => "Jean Michel Jarre",
                "album" => "Oxygène",
                "track_number" => 4,
                "genre_id" => 17,
                "name" => "Oxygène (Part IV)",
                "length" => "0:04:14",
                "year" => 1977,],
            [
                "id" => 45,
                "artist" => "AllttA",
                "album" => "Facing Giants",
                "track_number" => 1,
                "genre_id" => 24,
                "name" => "Snow Fire (fg. I) [feat. 20syl & Mr. J Medeiros]",
                "length" => "0:04:23",
                "year" => 2017,],
            [
                "id" => 46,
                "artist" => "Jean Michel Jarre",
                "album" => "Oxygène",
                "track_number" => 5,
                "genre_id" => 17,
                "name" => "Oxygène (Part V)",
                "length" => "0:10:23",
                "year" => 1977,],
            [
                "id" => 48,
                "artist" => "Jean Michel Jarre",
                "album" => "Oxygène",
                "track_number" => 6,
                "genre_id" => 17,
                "name" => "Oxygène (Part VI)",
                "length" => "0:06:20",
                "year" => 1977,],
            [
                "id" => 49,
                "artist" => "Lemongrass",
                "album" => "Windows",
                "track_number" => 1,
                "genre_id" => 6,
                "name" => "The Well",
                "length" => "0:01:33",
                "year" => 2001,],

            [
                "id" => 50,
                "artist" => "Tangerine Dream",
                "album" => "Rubycon",
                "track_number" => 1,
                "genre_id" => 17,
                "name" => "Rubycon, Part I",
                "length" => "0:17:19",
                "year" => 1975,],
        ];

        foreach ($seedTracks as $seed) {
            Track::create($seed);
        }
    }
}
